### ISSUE TITLE
vllm加速问题

### ISSUE THREAD

**Issue by dw199777** [liunian-Jay/MU-GOT#1]
python ./demo/run_ocr_2.0.py  --model-name  ./GOT_weights/  --image-file  ./img_test/1.png  --type ocr
作者您好，请问运行了以上命令会自动启用vllm加速功能吗？

**Comment by liunian-Jay** [comment]
> python ./demo/run_ocr_2.0.py --model-name ./GOT_weights/ --image-file ./img_test/1.png --type ocr 作者您好，请问运行了以上命令会自动启用vllm加速功能吗？

你好，这个命令是GOT运行源代码，不会自动启动加速的。你可以参考PDF_parsing/pic2tab.py中的vllm生成的过程，根据你的需求进行修改（另外，vllm版的模型是在PDF_parsing/__init__.py中加载，然后import到PDF_parsing/pic2tab.py中的）
