### ISSUE TITLE
单张图片也在推理时出现模型“秀逗”，不说人话

### ISSUE THREAD

**Issue by evanlin88** [liunian-Jay/MU-GOT#12]
是否有参数减少类似秀逗的情况？
![10192_10](https://github.com/user-attachments/assets/135a9f6d-5d9e-484a-acc0-1d07040475c2)
推理结果：
"response": "\\(: \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 } { 2 } \\cdot \\frac { 1 }"}

**Comment by dw199777** [comment]
type='ocr'试试

**Comment by evanlin88** [comment]
> type='ocr'试试

type='ocr'，没秀逗情况 了，

但因为统一接口处理，要公式格式接口处理；是否有一个检测方法，先判断是否有公式？
