### ISSUE TITLE
circular import

### ISSUE THREAD

**Issue by dw199777** [liunian-Jay/MU-GOT#4]
(MU_GOT) root@WIN-VUQIEURDREF:/mnt/f/MU-GOT-master/PDF_parsing# python pic2tab.py
Traceback (most recent call last):
  File "/mnt/f/MU-GOT-master/PDF_parsing/pic2tab.py", line 29, in <module>
    from __init__ import tokenizer, model, image_processor, image_processor_high
  File "/mnt/f/MU-GOT-master/PDF_parsing/__init__.py", line 22, in <module>
    from pic2tab import vllm_got
  File "/mnt/f/MU-GOT-master/PDF_parsing/pic2tab.py", line 29, in <module>
    from __init__ import tokenizer, model, image_processor, image_processor_high
ImportError: cannot import name 'tokenizer' from partially initialized module '__init__' (most likely due to a circular import) (/mnt/f/MU-GOT-master/PDF_parsing/__init__.py)  
您好，请问这个问题怎么解决呢？

**Comment by liunian-Jay** [comment]
你好，这个是因为循环import 的错误，PDF_parsing/__init__.py有错误，现在已经更正
主要为把其中的import的几个包修改到了在pdf2txt.py中import
from PDF_parsing.pdf2md import pdf2md
from PDF_parsing.pic2tab import vllm_got
from PDF_parsing.process_markdown import process_markdown

**Comment by dw199777** [comment]
> 你好，这个是因为循环import 的错误，PDF_parsing/**init**.py有错误，现在已经更正 主要为把其中的import的几个包修改到了在pdf2txt.py中import from PDF_parsing.pdf2md import pdf2md from PDF_parsing.pic2tab import vllm_got from PDF_parsing.process_markdown import process_markdown

好的谢谢您！
[rank0]:   File "/root/miniconda3/envs/MU_GOT/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/mnt/f/MU-GOT-master/PDF_parsing/GOT/GOT/model/vision_encoder/vary_b.py", line 313, in forward
[rank0]:   File "/root/miniconda3/envs/MU_GOT/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/mnt/f/MU-GOT-master/PDF_parsing/GOT/GOT/model/vision_encoder/vary_b.py", line 313, in forward
[rank0]:     attn = attn.softmax(dim=-1)
[rank0]: RuntimeError: CUDA error: unknown error
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
这个问题是因为什么呢？
