### ISSUE TITLE
请问vllm版本的got-ocr2，支持多卡运行不？

### ISSUE THREAD

**Issue by evanlin88** [liunian-Jay/MU-GOT#5]
我定义：model = LLM(model=model_name, max_model_len=8192,tensor_parallel_size=2, trust_remote_code=True)
然后执行启动：CUDA_VISIBLE_DEVICES=0,1 python run_ocr_vllm.py

报错：
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226] Exception in worker VllmWorkerProcess while processing method start_worker_execution_loop: Input type (float) and bias type (c10::BFloat16) should be the same, Traceback (most recent call last):
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 223, in _run_worker_process
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     output = executor(*args, **kwargs)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 65, in start_worker_execution_loop
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     output = self.execute_model(execute_model_req=None)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 272, in execute_model
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     output = self.model_runner.execute_model(
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1314, in execute_model
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     hidden_or_intermediate_states = model_executable(
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/got-ocr/vllm_got_ocr/vllm_got/GOT/GOT/model/modeling_GOT_vllm.py", line 390, in forward
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     hidden_states = self.model(
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/got-ocr/vllm_got_ocr/vllm_got/GOT/GOT/model/modeling_GOT_vllm.py", line 321, in forward
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     inputs_embeds = self.merge_embeddings(input_ids, inputs_embeds, images)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/got-ocr/vllm_got_ocr/vllm_got/GOT/GOT/model/modeling_GOT_vllm.py", line 239, in merge_embeddings
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     cnn_feature = self.vision_tower_high(image)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/got-ocr/vllm_got_ocr/vllm_got/GOT/GOT/model/vision_encoder/vary_b.py", line 181, in forward
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     x = self.patch_embed(x)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/got-ocr/vllm_got_ocr/vllm_got/GOT/GOT/model/vision_encoder/vary_b.py", line 469, in forward
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     x = self.proj(x)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     return self._conv_forward(input, self.weight, self.bias)
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]   File "/data/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]     return F.conv2d(input, weight, bias, self.stride,
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226] RuntimeError: Input type (float) and bias type (c10::BFloat16) should be the same
(VllmWorkerProcess pid=244400) ERROR 10-29 19:37:04 multiproc_worker_utils.py:226]
batch_size 1
input_ids torch.Size([1, 288])
inputs_embeds torch.Size([1, 288, 1024])
image_features torch.Size([1, 256, 1024])
inputs_embeds ------- torch.Size([288, 1024])

**Comment by liunian-Jay** [comment]
你好，这个实现没对多卡情况进行特殊的适配
