### ISSUE TITLE
vllm推理的效果，好像跟直接运行的效果有偏差

### ISSUE THREAD

**Issue by evanlin88** [liunian-Jay/MU-GOT#6]
模型（没用vllm）执行的效果是：\[\left\{ \begin{array}{l} x _ { 2 } = 2 \\ y _ { 2 } = 3 \end{array}\right.\]
模型（用vllm）执行的效果是：\[( - x _ { . } \left.- X , ^ { z }\right)^{ = ( r ) + n / e ] ^ { i }}- a c m < s ; g > b d y= f o t h( v u l p q k) : w\)

vllm代码：
sampling_param = SamplingParams(temperature=0, top_p=0.8, repetition_penalty=1.25, max_tokens=2048, stop_token_ids = new_keyword_ids)

    # stopping_criteria = KeywordsStoppingCriteria(keywords, tokenizer, input_ids)
    with torch.autocast("cuda", dtype=torch.bfloat16):
        output_ids = model.generate(
            prompts = [
                {
                    'prompt_token_ids': input_ids,
                    'multi_modal_data':{
                        'image':image_tensor.unsqueeze(0)
                    }
                } for image_tensor in image_tensors
            ],
            sampling_params = sampling_param
        )
        generated_text = ""
        for o in output_ids:
            print('-'*100,'\n\n')
            generated_text += o.outputs[0].text

单模型代码：
model = GOTQwenForCausalLM.from_pretrained(model_name, low_cpu_mem_usage=True, device_map='cuda', use_safetensors=True, pad_token_id=151643)
#model = AutoModel.from_pretrained(model_name, trust_remote_code=True, low_cpu_mem_usage=True, device_map='cuda', use_safetensors=True, pad_token_id=151643)
#model = AutoModelForCausalLM.from_pretrained(model_name, low_cpu_mem_usage=True, device_map='cuda', use_safetensors=True, pad_token_id=151643)

 
model.eval().to(device='cuda', dtype=torch.bfloat16)

**Comment by liunian-Jay** [comment]
解码参数那里可以试试调整下，
` sampling_param = SamplingParams(temperature=0.7, top_p=0.8, repetition_penalty=1.25, max_tokens=2048, stop_token_ids = new_keyword_ids)`
其余部分代码的几乎从GOT源码照搬过来的（不太确定有没有遗漏啥内容），模型内部的vllm加速细节是直接继承qwen2的，不太清楚这个会不会也造成偏差。

**Comment by evanlin88** [comment]
> 解码参数那里可以试试调整下， ` sampling_param = SamplingParams(temperature=0.7, top_p=0.8, repetition_penalty=1.25, max_tokens=2048, stop_token_ids = new_keyword_ids)` 其余部分代码的几乎从GOT源码照搬过来的（不太确定有没有遗漏啥内容），模型内部的vllm加速细节是直接继承qwen2的，不太清楚这个会不会也造成偏差。

我配置temperature=0了，但还是不行，是否其他参数还要改？

vllm模型加载，对比继承qwen2的模型加载；是否还有其他参数需保持一致？

**Comment by zhchbin** [comment]
@evanlin88 我目前用的参数，简单测试几个case能对齐输出结果。

```python
sampling_param = SamplingParams(
    temperature=0.0,
    top_p=0.9,
    top_k=50,
    repetition_penalty=1,
    max_tokens=2048,
    stop_token_ids=new_keyword_ids,
)
```

@liunian-Jay 感谢作者开源！

**Comment by evanlin88** [comment]
> @evanlin88 我目前用的参数，简单测试几个case能对齐输出结果。
> 
> ```python
> sampling_param = SamplingParams(
>     temperature=0.0,
>     top_p=0.9,
>     top_k=50,
>     repetition_penalty=1,
>     max_tokens=2048,
>     stop_token_ids=new_keyword_ids,
> )
> ```
> 
> @liunian-Jay 感谢作者开源！

@zhchbin 确实有改善哦，最起码不飘了，但还有部分不太准，已经好很多了。我再看看其他参数，感谢
